import pytest
pytestmark = [pytest.mark.m1, pytest.mark.skip(reason="M1 scope; specs in module docstrings & dev doc")]
def test_drift_synthetic_ramps(): ...
def test_sense_injection_100pct(): ...
def test_label_join_edge_cases(): ...
def test_valid_report_template(): ...
