/* quiz-bank.js —— 2026 A2L / EPA 608 诊断题库
 * 结构：questions[].options[].mc → misconceptions 表（错因诊断的知识底座）
 * 题目/诊断内容为英文（与真实考试一致）；正确项 mc 为 null。
 * 事实基准（2026-07 逐条核对）：
 *   - 2024 ERR 规则（89 FR 82682，泄漏修复 2026-01-01 生效：≥15 lb、GWP>53、触发率 10/20/30）
 *   - Technology Transitions（40 CFR 84 Subpart B）+ 2026-05-26 再审议最终规则（取消 R-410A 安装截止线）
 *   - 40 CFR 82 Subpart F（608 四类证 / 抽空表 / 排放禁令 / 80% 充装）
 *   - GWP 取 EPA AR4 口径：R-410A 2088 · R-32 675 · R-454B 466
 *   - ASHRAE 34/15.2、UL 60335-2-40、AHRI 过渡指南、Carrier/Chemours OEM 文档 */
window.QUIZ_BANK = {
  version: '2026.07',
  domains: ['a2l', 'core', 'rule26'],
  misconceptions: {
    mc_a3: {
      name: 'Treating A2L like propane (A3)',
      desc: 'You are mapping "flammable" straight to "explosive". A2L is its own class: high ignition energy, slow flame speed — a different risk profile from A3 hydrocarbons.',
      fix: 'A2L = lower toxicity + LOWER flammability: burning velocity ≤ 10 cm/s and hard to ignite. Respect ignition-source rules, but do not carry A3 assumptions into A2L work.',
      ref: 'ASHRAE 34 safety classes; ESCO "A2L Refrigerant Safety" course',
      plan: 'Re-read the ASHRAE 34 class matrix (A/B × 1/2L/2/3) until you can reproduce it from memory.',
    },
    mc_class: {
      name: 'ASHRAE 34 letter-number system is fuzzy',
      desc: 'The safety-class code is a two-axis system and you are blending the axes: the letter is toxicity, the number is flammability.',
      fix: 'A = lower toxicity, B = higher toxicity; 1 = no flame propagation, 2L = lower flammability (≤10 cm/s), 2 = flammable, 3 = higher flammability. R-32 and R-454B are both A2L.',
      ref: 'ASHRAE Standard 34, Section 6',
      plan: 'Make a 2×4 flash card of the ASHRAE 34 matrix with one example refrigerant per cell.',
    },
    mc_retrofit: {
      name: 'Thinking A2L is a drop-in retrofit',
      desc: 'You are treating the R-410A → A2L change like R-22 → R-407C. It is not a retrofit path: A2L safety design (sensors, airflow, ignition control) is built into listed new equipment.',
      fix: 'Never charge an A2L refrigerant into a system listed for R-410A — it violates the UL 60335-2-40 listing, codes, and manufacturer instructions. A2L refrigerants go only into equipment designed and listed for them.',
      ref: 'UL 60335-2-40; OEM bulletins (Carrier/Daikin) on R-454B & R-32',
      plan: 'Memorize the one-liner: "A2L is a platform change, not a retrofit."',
    },
    mc_service_ban: {
      name: 'Overcorrecting: "R-410A is now illegal"',
      desc: 'You have over-applied the 2025/2026 transition: the bans target NEW equipment, not the installed base.',
      fix: 'Existing R-410A systems may be serviced and repaired indefinitely — with virgin (while supplies last), recovered or reclaimed R-410A. What ended is installing new R-410A systems, not servicing old ones.',
      ref: 'EPA Technology Transitions FAQ; AIM Act phasedown schedule',
      plan: 'Learn the transition as two lists: what is banned (new equipment) vs what continues (service, reclaim).',
    },
    mc_tools: {
      name: 'A2L tool compatibility is guesswork',
      desc: 'Either "all my R-410A tools are fine" or "I must re-buy everything" — both cost you: one is a safety/compliance risk, the other wastes money.',
      fix: 'Must be A2L-rated: recovery machine (spark-free) and electronic leak detector (UL/EN listed for A2L). Generally carry over: gauges, hoses (check ratings), scales, and most vacuum pumps — verify manufacturer listing.',
      ref: 'AHRI Safe Refrigerant Transition Task Force guidance; tool OEM A2L compatibility lists',
      plan: 'Audit your kit against an OEM A2L-compatibility list and tag each tool OK / replace.',
    },
    mc_props: {
      name: 'Guessing A2L pressures & behavior instead of using data',
      desc: 'You are extrapolating from R-410A habits instead of the actual property data of the new refrigerants.',
      fix: 'R-454B runs close to R-410A with slightly LOWER pressures and a small (~1.5°F) glide; R-32 runs similar-to-slightly-higher pressures with notably hotter discharge. Always use the PT chart for the actual refrigerant.',
      ref: 'OEM PT charts; this site\'s Refrigerant Properties tool (R-32 / R-454B included)',
      plan: 'Pull up R-32 and R-454B on the refrigerant-properties tool and compare saturation pressures with R-410A at 45°F / 105°F.',
    },
    mc_gwp: {
      name: 'Confusing "lower GWP" with "no GWP / no rules"',
      desc: 'Low-GWP marketing language has slid into "environmentally free pass" in your model of the rules.',
      fix: 'R-454B GWP ≈ 466 and R-32 ≈ 675 — roughly 78% / 68% below R-410A (≈2088), but far from zero. Venting and recovery rules apply to A2Ls exactly as to other regulated refrigerants.',
      ref: 'AR4/AR5 GWP tables; EPA venting prohibition (CAA §608(c))',
      plan: 'Memorize three GWP anchors: R-410A ≈ 2088, R-32 ≈ 675, R-454B ≈ 466.',
    },
    mc_charge: {
      name: 'Blend-charging rules half-remembered',
      desc: 'Fractionation logic is inverted in your recall: blends separate in the VAPOR phase, so you avoid that by moving liquid.',
      fix: 'Charge zeotropic/near-azeotropic blends (R-454B, like R-410A before it) as LIQUID from the cylinder, metering into the suction side as needed. Single-component R-32 has no glide and can be charged in either phase and topped off freely.',
      ref: 'OEM charging instructions; manifold/cylinder markings',
      plan: 'Write the rule once: "Blends leave the tank as liquid; singles don\'t care."',
    },
    mc_vent: {
      name: 'Venting legality reasoned from ODP/GWP instead of the rule',
      desc: 'You are deciding what may be released based on "does it harm ozone / climate" logic. The law does not work that way — it names what is prohibited and what is exempt.',
      fix: 'Knowingly venting ANY regulated refrigerant or substitute (CFC, HCFC, HFC, HFO/A2L blends) is illegal — currently up to $124,426 per day per violation. Exemptions are specific and listed by EPA (e.g., de minimis releases during good-faith recovery, nitrogen holding charges, and certain exempted substitutes like CO₂). "Low GWP" is not an exemption.',
      ref: '40 CFR 82.154; EPA Section 608 venting prohibition fact sheet',
      plan: 'Memorize the short exemption list — everything not on it stays in the system or the cylinder.',
    },
    mc_evac: {
      name: 'Recovery evacuation requirements not solid',
      desc: 'Two separate vacuums are blending together: the EPA recovery table (inches Hg, depends on appliance size/class) and the deep-vacuum dehydration target (microns) used before recharging.',
      fix: 'Recovery: EPA table sets inches-Hg targets by appliance class/size and recovery-machine vintage (e.g., R-22 ≥200 lbs → 10 in Hg with a post-1993 machine). Dehydration/evacuation before charging: 500 microns is industry practice, not an EPA recovery number.',
      ref: '40 CFR 82.156 required-evacuation tables; EPA 608 Type II prep material',
      plan: 'Print the EPA evacuation table and quiz yourself until the R-22 rows are automatic.',
    },
    mc_rrr: {
      name: 'Recover / recycle / reclaim blurred',
      desc: 'The three R\'s differ by WHERE the refrigerant can go next — that is the part your definitions are missing.',
      fix: 'Recover = remove and store, no processing. Recycle = on-site cleanup (oil separation, filter-driers), reuse in same/same-owner equipment. Reclaim = reprocess to AHRI 700 purity with chemical analysis — required before refrigerant changes ownership; done by EPA-certified reclaimers.',
      ref: 'EPA 608 Core definitions; AHRI Standard 700',
      plan: 'Anchor each R to its destination: same system / same owner / open market.',
    },
    mc_cyl: {
      name: 'Cylinder handling by feel, not by rule',
      desc: 'Fill limits and cylinder rules exist to keep hydrostatic pressure from turning a tank into a projectile — they are exam favorites precisely because people wing them.',
      fix: 'Recovery cylinders: fill to max 80% of capacity, use DOT-approved recovery cylinders (yellow top / gray body), never mix refrigerants in one tank, and transport upright & secured.',
      ref: 'DOT 49 CFR; EPA 608 Core cylinder-safety section',
      plan: 'Remember "80 / DOT / don\'t mix / upright" as one phrase.',
    },
    mc_hfc_scope: {
      name: 'Stuck in the pre-2026 "608 = ozone only" world',
      desc: 'Your mental model of Section 608 stops at CFC/HCFC. Since the AIM Act and the 2024 Refrigerant Management (ERR) rule, HFCs and their substitutes are inside the management regime.',
      fix: 'From January 1, 2026, leak-repair and related refrigerant-management requirements apply to appliances with ≥15 lbs of HFC or HFC-substitute refrigerant (GWP > 53) — and 608 certification is required to handle A2Ls like R-32/R-454B.',
      ref: 'EPA 2024 ERR (Emissions Reduction & Reclamation) rule; AIM Act subsections',
      plan: 'Update your 608 notes: scope now includes HFCs/A2Ls — mark every "ODS-only" statement as outdated.',
    },
    mc_thresholds: {
      name: 'Leak-rate trigger numbers shuffled',
      desc: 'The three trigger rates are easy to transpose under exam pressure — and one of them almost certainly appears on your test.',
      fix: 'Annualized leak-rate triggers: 10% comfort cooling · 20% commercial refrigeration · 30% industrial process refrigeration. (Applies to appliances above the charge threshold — ≥15 lbs for HFCs under the 2026 ERR provisions.)',
      ref: 'EPA leak-repair requirements table (ERR rule)',
      plan: 'Mnemonic: "10 cool, 20 store, 30 plant."',
    },
    mc_dates: {
      name: 'Running on last year\'s transition headlines',
      desc: 'The transition rules MOVED in 2026 and your recall is a snapshot of the old coverage: the famous "no R-410A installs after Jan 1 2026" deadline was first bridged by enforcement discretion, then permanently removed by EPA\'s May 2026 reconsideration rule.',
      fix: 'What stands: since Jan 1 2025, no manufacture/import of new residential & light-commercial AC/HP products using refrigerants with GWP ≥ 700 (e.g., R-410A). What changed: the Jan 1 2026 installation deadline is gone — systems built from pre-2025 components may be installed until supplies run out (VRF has its own later dates).',
      ref: 'EPA Technology Transitions reconsideration final rule (May 26, 2026; effective July 27, 2026)',
      plan: 'Update your notes: 2025 = "no new R-410A boxes built" still true; the install deadline was REMOVED in May 2026 — track the rule, not the headline.',
    },
    mc_a2l_cert: {
      name: 'Inventing a separate "EPA A2L license"',
      desc: 'Manufacturers, distributors and some AHJs require A2L training — your brain has upgraded that into a new federal certification that does not exist.',
      fix: 'EPA Section 608 remains THE federal certification for handling regulated refrigerants, including A2Ls. A2L safety training (ESCO, OEM, ACCA) is strongly expected — and often required by employers/suppliers — but it is not a separate EPA card.',
      ref: 'EPA 608 program pages; ESCO A2L training program description',
      plan: 'Keep the two layers separate in your notes: federal 608 certification vs industry A2L training.',
    },
  },

  questions: [
    {
      id: 'q1', domain: 'a2l',
      text: 'Under ASHRAE Standard 34, what does the "A2L" classification of R-32 and R-454B actually mean?',
      options: [
        { t: 'Lower toxicity, and lower flammability — a maximum burning velocity of 10 cm/s or less, with high ignition energy', mc: null },
        { t: 'Roughly as flammable as propane, so the same jobsite rules as A3 refrigerants apply', mc: 'mc_a3', why: 'A3 (propane) burns ~5× faster and ignites far more easily. A2L is a deliberately separate class: slow flame speed (≤10 cm/s), hard to ignite.' },
        { t: 'Higher toxicity but no flame propagation — the "L" stands for "low toxicity limit"', mc: 'mc_class', why: 'The letter carries toxicity (A = lower, B = higher); the number carries flammability. "L" marks the low-burning-velocity subclass of class 2.' },
        { t: '"A" means approved for occupied spaces and "2L" means a 2-lb charge limit', mc: 'mc_class', why: 'Charge limits come from ASHRAE 15.2 / UL 60335-2-40 calculations, not from the safety-class code itself.' },
      ],
      answer: 0,
      why: 'A2L = lower toxicity (A) + lower flammability (2L): burning velocity ≤ 10 cm/s and high ignition energy. That is why A2Ls get their own handling rules rather than A3 rules.',
      ref: 'ASHRAE 34 §6; ESCO A2L safety curriculum',
    },
    {
      id: 'q2', domain: 'a2l',
      text: 'A customer\'s R-410A condenser is dead, and they ask you to "just convert" the existing system to R-454B to be future-proof. What is the correct call in 2026?',
      options: [
        { t: 'Decline the retrofit: A2L refrigerants may only be used in new equipment designed and listed for them', mc: null },
        { t: 'Do it — swap the TXV, flush the oil, and R-454B will run fine on the old platform', mc: 'mc_retrofit', why: 'Mechanically it might run, which is the trap. The system lacks the A2L safety design (leak sensors, airflow logic, ignition-safe components) and the listing that makes it legal.' },
        { t: 'Do it as long as the total charge stays under the room\'s ASHRAE 15.2 charge limit', mc: 'mc_retrofit', why: 'Charge limits apply to listed A2L equipment. They do not authorize charging A2L into equipment never listed for a flammable refrigerant.' },
        { t: 'Replace the whole system either way — servicing R-410A equipment became illegal in 2026', mc: 'mc_service_ban', why: 'Servicing the existing R-410A installed base remains fully legal. The 2025/2026 restrictions target new equipment, not repairs.' },
      ],
      answer: 0,
      why: 'Retrofitting an R-410A system to an A2L violates the UL 60335-2-40 listing, mechanical codes, and every OEM instruction. A2L is a new-equipment platform change, not a retrofit path.',
      ref: 'UL 60335-2-40; Carrier/Daikin R-454B & R-32 service bulletins',
    },
    {
      id: 'q3', domain: 'a2l',
      text: 'You are outfitting your truck for R-454B work. Which statement about tooling is correct?',
      options: [
        { t: 'The recovery machine and electronic leak detector must be A2L-rated; gauges, scales and most vacuum pumps carry over if rated for the pressures', mc: null },
        { t: 'All existing R-410A tools are fine — A2L is barely flammable, so nothing changes', mc: 'mc_tools', why: 'Two tools genuinely change: recovery machines must be spark-free/A2L-listed, and leak detectors must be listed to sense A2Ls safely. Skipping those is a real safety and compliance gap.' },
        { t: 'Every tool that touches refrigerant must be replaced with an A2L-listed version, including manifolds and scales', mc: 'mc_tools', why: 'That over-replacement wastes hundreds of dollars. Passive tools (manifolds, hoses within rating, scales) and most vacuum pumps are fine — check the manufacturer\'s listing.' },
        { t: 'Only new hoses are required; everything else including the recovery machine is compatible', mc: 'mc_tools', why: 'Backwards — hoses are usually the part that carries over (check ratings), while the recovery machine is exactly the tool that must be A2L-rated.' },
      ],
      answer: 0,
      why: 'A2L-specific: spark-free recovery machine + A2L-listed leak detector. Most passive tools and vacuum pumps carry over — verify against the manufacturer\'s A2L compatibility list.',
      ref: 'AHRI Safe Refrigerant Transition guidance; tool OEM compatibility lists',
    },
    {
      id: 'q4', domain: 'a2l',
      text: 'Compared with the R-410A systems you know, which statement about R-454B (Opteon XL41 / Puron Advance) is TRUE?',
      options: [
        { t: 'It runs slightly lower pressures than R-410A, with a small temperature glide around 1.5°F, and a GWP roughly 78% lower', mc: null },
        { t: 'It is a drop-in replacement, so pressures and service procedures are identical to R-410A', mc: 'mc_retrofit', why: '"Close to R-410A" made R-454B attractive to OEMs, but drop-in it is not: A2L equipment, sensors and handling rules are different even though gauges look familiar.' },
        { t: 'Its GWP is effectively zero, which is why the EPA exempted it from venting rules', mc: 'mc_gwp', why: 'R-454B\'s GWP is ≈466 — much lower than R-410A\'s ≈2088, but nowhere near zero, and venting it is just as illegal.' },
        { t: 'Being a blend, it must be charged as vapor to avoid fractionation', mc: 'mc_charge', why: 'Inverted: blends fractionate when vapor is drawn off. You charge blends as LIQUID from the cylinder — same habit as R-410A.' },
      ],
      answer: 0,
      why: 'R-454B ≈ R-32/R-1234yf blend: pressures slightly below R-410A (per Carrier/Chemours OEM data), ~1.5°F glide (near-azeotropic), GWP 466 vs R-410A\'s 2088. Familiar-feeling, but legally and procedurally a new platform.',
      ref: 'Carrier R-454B FAQ; Chemours Opteon XL41 datasheet; OEM PT charts',
    },
    {
      id: 'q5', domain: 'a2l',
      text: 'You need to unsweat a fitting on an R-32 system that just lost its compressor. Which prep sequence is right?',
      options: [
        { t: 'Recover the full charge with an A2L-rated machine, pull/verify no refrigerant remains, flow nitrogen while brazing, keep ignition control until verified clear', mc: null },
        { t: 'R-32\'s GWP is low, so venting the small remaining charge outdoors before brazing is acceptable', mc: 'mc_vent', why: 'Venting any regulated substitute — including A2Ls — is illegal regardless of GWP. Low-GWP ≠ vent-legal.' },
        { t: 'Since the system is dead, braze straight away — a torch will simply burn off any refrigerant left in the lines', mc: 'mc_a3', why: 'This is the flammability risk taken to the opposite extreme: refrigerant + flame in a confined line can ignite and also produces toxic decomposition products (HF). Recover and purge first — that rule predates A2L and matters more now.' },
        { t: 'Recover to atmospheric pressure only; a deep pull is not required because A2Ls self-dissipate', mc: 'mc_evac', why: '"Self-dissipating" is not a recovery standard. EPA evacuation requirements apply to A2L systems like any other — recover to the required level before opening.' },
      ],
      answer: 0,
      why: 'Full recovery with A2L-rated equipment → verify zero refrigerant → nitrogen flow while brazing → maintain ignition-source control. Same craftsmanship as before, with flammability discipline added.',
      ref: 'ESCO A2L service procedures; AHRI transition guidance',
    },
    {
      id: 'q6', domain: 'core',
      text: 'A supermarket sells its used refrigerant to another company. Before that refrigerant can legally change hands for reuse, it must be:',
      options: [
        { t: 'Reclaimed — reprocessed to AHRI 700 purity and chemically verified, typically by an EPA-certified reclaimer', mc: null },
        { t: 'Recycled — run through an on-site recycling machine with fresh filter-driers', mc: 'mc_rrr', why: 'Recycling only cleans refrigerant enough for reuse within the same owner\'s equipment. Crossing an ownership boundary is exactly what triggers the reclaim requirement.' },
        { t: 'Recovered — as long as it was removed with certified recovery equipment, it can be resold as-is', mc: 'mc_rrr', why: 'Recovery is just removal and storage — no processing at all. Recovered refrigerant cannot enter the market without reclamation.' },
        { t: 'Re-blended by any wholesaler to match the original composition specification', mc: 'mc_rrr', why: '"Re-blending by a wholesaler" is not a Section 608 category. Purity restoration to AHRI 700 with lab verification is what the rule requires — that is reclamation.' },
      ],
      answer: 0,
      why: 'The three R\'s differ by destination: recover = remove/store; recycle = on-site cleanup for same-owner reuse; reclaim = AHRI 700 purity + chemical analysis, required before refrigerant changes ownership.',
      ref: 'EPA 608 Core; AHRI Standard 700',
    },
    {
      id: 'q7', domain: 'core',
      text: 'You are recovering R-22 from a 300-lb commercial system using a recovery machine built in 2020. Per EPA, you must evacuate the appliance to:',
      options: [
        { t: '10 inches Hg vacuum', mc: null },
        { t: '0 inches Hg (atmospheric) — that is the R-22 requirement', mc: 'mc_evac', why: '0 in Hg applies to HCFC-22 appliances containing LESS than 200 lbs. At 300 lbs you are in the ≥200-lb row: 10 in Hg.' },
        { t: '500 microns', mc: 'mc_evac', why: 'Microns belong to dehydration/evacuation before recharging — an industry practice, not an EPA recovery level. The recovery table is written in inches Hg.' },
        { t: '15 inches Hg vacuum', mc: 'mc_evac', why: '15 in Hg is the deepest table value (very-high-pressure/other rows) — over-recall. The R-22 ≥200 lbs row with a post-1993 machine is 10 in Hg.' },
      ],
      answer: 0,
      why: 'EPA required-evacuation table: HCFC-22 appliance ≥200 lbs, recovery equipment manufactured after Nov 15 1993 → 10 in Hg vacuum. (<200 lbs → 0 in Hg.) Separate concept from the 500-micron dehydration pull.',
      ref: '40 CFR 82.156 evacuation tables (EPA 608 Type II)',
    },
    {
      id: 'q8', domain: 'core',
      text: 'Which of these releases is actually LEGAL under the Section 608 venting prohibition?',
      options: [
        { t: 'The de minimis refrigerant that escapes while making a good-faith connection or disconnection during recovery', mc: null },
        { t: 'Venting R-410A, because it contains no chlorine and does not harm the ozone layer', mc: 'mc_vent', why: 'The venting prohibition was extended to HFC substitutes back in 1995. Zero ODP does not make release legal.' },
        { t: 'Venting a small A2L charge, because its GWP is under the 700 threshold', mc: 'mc_vent', why: 'The GWP-700 line is an equipment-manufacturing rule (Technology Transitions), not a venting exemption. Venting A2Ls is illegal.' },
        { t: 'Blowing refrigerant through a clogged filter-drier to clear debris from the line', mc: 'mc_vent', why: 'Using system refrigerant as a "blow-out gas" is a knowing release — a classic exam distractor and a real fine in the field. Use recovered charge + nitrogen instead.' },
      ],
      answer: 0,
      why: 'Legal releases are a short, specific list: de minimis escape during good-faith recovery practices, nitrogen holding charges, and a few EPA-exempted substitutes in listed applications. Everything else stays in the system or the tank.',
      ref: '40 CFR 82.154; EPA venting-prohibition fact sheet',
    },
    {
      id: 'q9', domain: 'core',
      text: 'When filling a recovery cylinder, you stop at 80% of its capacity. Why 80%?',
      options: [
        { t: 'To leave expansion room so rising temperature cannot hydrostatically over-pressurize the cylinder', mc: null },
        { t: 'To keep the cylinder light enough for one-person DOT-legal lifting', mc: 'mc_cyl', why: 'Ergonomics is not the rule\'s basis — liquid expansion is. A hydrostatically full cylinder can rupture with lethal force as temperature rises.' },
        { t: 'Because the last 20% of any cylinder is non-condensables by design', mc: 'mc_cyl', why: 'Non-condensables are a contamination issue diagnosed by pressure checks — nothing to do with the fill limit.' },
        { t: 'It is only a manufacturer recommendation; filling to 95% is acceptable when the tank is kept cool', mc: 'mc_cyl', why: 'The 80% fill limit is a hard safety rule (DOT/EPA exam material), not a soft recommendation — "keeping it cool" is not a control you can guarantee in a truck.' },
      ],
      answer: 0,
      why: 'Liquid refrigerant expands with temperature. The 80% limit preserves vapor space so the cylinder cannot go hydrostatically solid and rupture. Pair it with: DOT-approved cylinder, never mix refrigerants, transport upright.',
      ref: 'EPA 608 Core cylinder safety; DOT 49 CFR',
    },
    {
      id: 'q10', domain: 'rule26',
      text: 'July 2026: a rooftop comfort-cooling unit holding 40 lbs of R-454B is losing charge. Under the EPA\'s refrigerant-management (ERR) requirements now in force, what applies?',
      options: [
        { t: 'It is covered: appliances with ≥15 lbs of HFC/substitute refrigerant must be repaired if the annualized leak rate exceeds 10% for comfort cooling', mc: null },
        { t: 'Nothing — leak-repair requirements only apply to ozone-depleting refrigerants like R-22', mc: 'mc_hfc_scope', why: 'That was true before the AIM Act era. As of Jan 1 2026, leak-repair obligations extend to HFCs and substitutes (GWP > 53) at a 15-lb charge threshold — R-454B qualifies.' },
        { t: 'It is covered, but the comfort-cooling trigger rate is 30% per year', mc: 'mc_thresholds', why: '30% is the INDUSTRIAL PROCESS trigger. Comfort cooling is the strictest: 10%.' },
        { t: 'It is exempt because the charge is under the 50-lb threshold that applies to all appliances', mc: 'mc_hfc_scope', why: '50 lbs was the old ODS-era threshold. The 2024 ERR rule set 15 lbs for HFC-era appliances — a major 2026 exam update.' },
      ],
      answer: 0,
      why: 'The 2024 ERR rule (leak-repair provisions effective Jan 1 2026) covers appliances with ≥15 lbs of HFC or substitute refrigerant with GWP > 53. Triggers: 10% comfort cooling · 20% commercial refrigeration · 30% industrial process.',
      ref: 'EPA Emissions Reduction & Reclamation rule (2024), leak-repair subpart',
    },
    {
      id: 'q11', domain: 'rule26',
      text: 'July 2026: a supply house still has brand-new R-410A split-system components on the shelf (manufactured before January 1, 2025). For a new residential install, a contractor may:',
      options: [
        { t: 'Install them — EPA\'s May 2026 reconsideration rule removed the January 1, 2026 installation deadline, so pre-2025-built systems may be installed until supplies run out', mc: null },
        { t: 'Not install them — installing new R-410A systems became illegal nationwide on January 1, 2026', mc: 'mc_dates', why: 'That WAS the original rule — which is exactly why this distractor works. EPA bridged the deadline with enforcement discretion in 2025 and then permanently removed it in the May 2026 reconsideration rule.' },
        { t: 'Install them, and OEMs may also resume building new R-410A condensing units while demand lasts', mc: 'mc_dates', why: 'Half the update swallowed the other half: the manufacture/import prohibition (GWP ≥ 700, from Jan 1 2025) still stands — only the downstream INSTALLATION deadline was removed.' },
        { t: 'Not install them, and existing R-410A systems can no longer be recharged either', mc: 'mc_service_ban', why: 'Doubly overcorrected: installs of pre-2025-built stock are allowed again, and servicing/recharging the existing installed base was never prohibited.' },
      ],
      answer: 0,
      why: 'A genuinely 2026 fact: the manufacture/import ban (GWP ≥ 700) from Jan 1 2025 still stands, but EPA\'s reconsideration final rule (published May 26, 2026) removed the Jan 1 2026 installation cutoff — R-410A systems built from pre-2025 components may be installed until stock runs out. Stay current: the rules moved twice in 18 months.',
      ref: 'EPA Technology Transitions reconsideration final rule (May 2026); 40 CFR 84 Subpart B',
    },
    {
      id: 'q12', domain: 'rule26',
      text: 'What federal certification do you need to purchase and handle R-32 and R-454B in 2026?',
      options: [
        { t: 'EPA Section 608 certification — the venting/handling rules extend to substitutes; A2L safety training is expected by employers and suppliers but is not a separate federal card', mc: null },
        { t: 'A new "EPA A2L endorsement" that must be added to your 608 card', mc: 'mc_a2l_cert', why: 'No such federal endorsement exists. A2L training programs (ESCO, OEM, ACCA) are industry requirements, not an EPA certification category.' },
        { t: 'None — A2Ls are not ozone-depleting, so Section 608 does not apply to them', mc: 'mc_hfc_scope', why: 'Section 608\'s prohibitions and sales restrictions reach substitutes, and the 2026 refrigerant-management regime explicitly covers HFC/A2L refrigerants. 608 certification is required.' },
        { t: 'Only Universal certification holders may handle A2Ls; Type II is insufficient for split systems', mc: 'mc_a2l_cert', why: 'The Type I/II/III/Universal structure is about equipment category (small appliances / high-pressure / low-pressure), not refrigerant flammability class. Type II covers residential split systems regardless of A2L.' },
      ],
      answer: 0,
      why: 'Section 608 remains the federal certification for regulated refrigerants including A2L substitutes. Expect employers, distributors and AHJs to also require documented A2L safety training — but that is industry practice layered on top, not a new EPA license.',
      ref: 'EPA Section 608 program; ESCO A2L training program',
    },
  ],
};
